### ISSUE TITLE
[Question]: Does this only support Ubuntu instances?

### ISSUE THREAD

**Issue by prologic** [libersoft/proxmox-init#1]
Hi, I came across this because I was playing around with ProxMox VE 4.x (_which I have a full installation of here_) and got interested in how cloud-init works. Does proxmox-init currently only support Ubuntu? Do you still use this? What would it take to support other types of instances?

**Comment by lgaggini** [comment]
Hi, 
thank you for your interest in proxmox-init.
it should work with every cloud images supporting cloud-init, you can check the cloud-init doc for some more info: https://cloudinit.readthedocs.org/en/latest/topics/availability.html.
At the moment I'm not using proxmox-init and the development is stalling.

**Comment by prologic** [comment]
Thanks for the info! cheers
